### ISSUE TITLE
Firefox whalevault link leads nowhere

### ISSUE THREAD

**Issue by sxiii** [alexpmorris/WhaleVault#1]
The title says it all, while trying to reach the URL:

https://addons.mozilla.org/en-US/firefox/addon/whalevault/

Result:

Oops! We can’t find that page

Screenshot:
![image](https://user-images.githubusercontent.com/575925/81631985-6fd3f600-9409-11ea-8596-1cc2322564c1.png)

**Comment by alexpmorris** [comment]
firefox requested a few changes to better comply with their latest add-on requirement, hence why they removed past versions.  The latest version has now been accepted by firefox.  The chrome version is currently pending review.

Remember that you can always install the latest available version of the extension directly from https://github.com/alexpmorris/WhaleVault/releases if such a problem arises again.  

The problem with that approach is that you'll have to manually update.  WhaleVault does however provide a warning if your current version is out of date.

Latest version 0.1.27:

* added chain support for hive and blurt
* some minor changes to better comply with firefox's latest add-on requirements
* added polyfill support for Hive Keychain

WhaleVault can now be used to login and sign transactions directly on both Steem and Hive, along with their respective wallets, as well as for Steem-Engine and Hive-Engine!
