### ISSUE TITLE
Whalevault v0.1.48 auto locks itself after a period of time on Brave browser

### ISSUE THREAD

**Issue by cracklejoy** [alexpmorris/WhaleVault#11]
It seems like the autolocking mechanism of v0.1.48 is always running.  

My autolock is set to default (lock WhaleVault manually or when the browser is closed).  After some time WhaleVault will lock itself without any intervention as if the idle lock setting is enabled.  

This did not occur on the last revision of the extension.  

Running this on the current revision of Brave v1.62.165 (Feb 14, 2024).  I've backed up my settings and restored them along with a fresh reinstallation of the extension yet I see the same behavior.  As it stands this behavior makes the extension unusable in its current form.

**Comment by alexpmorris** [comment]
It's not the autolock. It has to do with Chrome forcing by mid-year all extensions to update to Manifest v3, which causes all sorts of issues with persistence. Firefox has not yet fully embraced v3 either, thus the need for two separate versions.

0.1.48 works perfectly when loaded directly with both the latest Chrome and Brave browsers. Unfortunately, it appears to behave differently when the same code is installed from the `chrome web store`.

I am working on another potential fix, but won't know for sure it works until it's upload and installed again from the `chrome web store`.

In the meantime, if you're somewhat tech-savvy, you can try installing the extension directly to your browser from the latest github releases here:

https://github.com/alexpmorris/WhaleVault/releases

Don't forget to `Backup Vault` first so you can easily restore your latest keys and settings.

**Comment by cracklejoy** [comment]
I can confirm that manually installing the extension does indeed fix the issue.  

Given that my v0.1.48 installation updated itself based off a chrome web store install people will soon be experiencing some issues once they notice it.

Thanks for the insight and hopefully a working chrome web store fix in the future.

**Comment by cracklejoy** [comment]
I've noticed that even with installing the extension manually it will lock itself after some amount of time even with the default auto-lock settings enabled.  Unlike the chrome web store install that locks me out after minutes, the manual install locks me out after a few days.

**Comment by alexpmorris** [comment]
I had whalevault (loaded locally) running in both chrome and brave for two weeks straight and never had the unload issue, so not sure what was going on for you.

Good news though is that I uploaded a new version `0.1.49` to the chrome store, and it's been running now for several days without unloading. So, hopefully that will finally fix the issue for you as well:

https://chromewebstore.google.com/detail/whalevault/hcoigoaekhfajcoingnngmfjdidhmdon

**Comment by cracklejoy** [comment]
The new version appears to have fixed the issues.  Thanks.

**Comment by alexpmorris** [comment]
Great to hear!
