### ISSUE TITLE
Posting comments with PeakD and Steempeak not working.

### ISSUE THREAD

**Issue by krischik** [alexpmorris/WhaleVault#4]
I noticed that it is not possible to post comments using PeakD and Steempeak when using WhaleVault. All other functions in particular, posting blogs and upvoting work just fine.

Which is also why I run into Issue #2 as I needed to temporarily deactivate WhaleVault to post a comment and confirm that it is indeed the combination of WhaleVault and PeakD/Steempeak.

It could of course be that PeakD/Steempeak are at fault.

**Comment by alexpmorris** [comment]
The keychain `post` polyfill method wasn't fully implemented properly, which is used by PeakD.  

This should be fixed in latest release v0.1.43

**Comment by krischik** [comment]
Thanks for the feedback. I'll try it out again.
