### ISSUE TITLE
Cancel order on hive engine not working.

### ISSUE THREAD

**Issue by krischik** [alexpmorris/WhaleVault#5]
I also noted that canceling an order on hive engine did not work as well. I'm not sure but I think placing an order did work.

Again, this might be an hive engine problem.

**Comment by alexpmorris** [comment]
unless you can show me some sort of error message, this is most likely an issue with Hive Engine.  Also, be sure to mention the browser you use. Extensions can be sort of iffy, and depend on the browser.  Also, depending on the browser, some glitches we've tried to address more browser related and not easily fixable from within the extension without requiring extensive work-arounds, if at all.
