### ISSUE TITLE
Blank screen issue when attempting to create a comment.

### ISSUE THREAD

**Issue by cracklejoy** [alexpmorris/WhaleVault#9]
I have a strange issue when replying to comments after a day or so of being logged into ecency.com using WhaleVault under Firefox.

I am logged in properly and when I type a single letter into the comment box my browser changes into a blank white screen.  I noticed if I clear out any cookies from ecency and log back in using WhaleVault I can reply only until the next day when the problem surfaces again.

I'm not sure if this is an ecency.com issue or a WhaleVault issue.

Any suggestions? This is extremely annoying. Thanks.
![ecency_whalevault_issue](https://user-images.githubusercontent.com/65365730/154351083-e1ab65a1-4f5a-4fc5-bf34-380fcb5cc5a4.gif)

**Comment by alexpmorris** [comment]
Not sure about that blank screen issue, but it doesn't seem WhaleVault is currently fully compatible with ecency.com, which seems to be attempting to use the `requestAddAccountAuthority` *(not currently supported as a polyfill by WhaleVault)* to provide `ecency.app` with the ability to post directly to your account, as opposed to using WhaleVault to directly sign and broadcast your post/comment transactions.

Technically, this feature is probably relatively easy to add. However, it also seems extra risky as it has the potential to let apps completely bypass WhaleVault *(or KeyChain for that matter)* for the requested scope.

HOWEVER, you probably don't have *this* particular issue if ecency has already added that scope to your account another way in the past. And if `ecency.app` can already post and comment on your behalf, it seems unlikely the problem resides with WhaleVault, as ecency would not even use WhaleVault for posting. 

In fact, just playing around a bit with the `guest123` account, I received the following error, despite WhaleVault having the posting key available:

`The app @ecency.app doesn't have permission to broadcast for @guest123`.

As far as your blank screen issue, keep the Chrome Console window open and see if there are any errors shown there when it happens that can provide more insight into what the problem may be.

**Comment by cracklejoy** [comment]
I appear to be getting the following according to the Firefox console.

DOMException: The quota has been exceeded. client.9663de42.js:2:4323600
Uncaught DOMException: The quota has been exceeded. client.9663de42.js:2

This isn't very helpful but your explanation is.  I see there are numerous other issues with ecency, I'll try using another frontend and see how things go. 

Thanks for the quick response.

**Comment by alexpmorris** [comment]
Seems you may be running out of IndexedDB space in firefox *(there is a limit to how much data can be saved by each website in the browser's DB)*. 

If you continue to use ecency.com, maybe this link can help with that:

https://support.mozilla.org/de/questions/1309735

**Comment by cracklejoy** [comment]
This indeed is a strange cookie issue on their site that I've never run across before.  The cookie keeps increasing in size for some reason.

You can increase the available cookie size in Firefox but you'll eventually hit the limit again and reproduce this error.

ecency DOMException: The quota has been exceeded in console

Type about:config in Firefox
Change the following entry  
dom.storage.default_quota 5120 (default)

I've changed it to 10 megabytes a few days ago and it's filled up yet again :/
